POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = custom

PS2_MOUSE_ENABLE = no
PS2_ENABLE = yes
PS2_USE_USART = yes
MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes

SPLIT_KEYBOARD = yes

SRC += my_pointing_device.c